export const fields = {
  activity: {
    place: '',
    description: '',
    date: '',
    time: '',
  },
  car: {
    agency: '',
    notes: '',
    pick_Up_Location: '',
    pick_Up_Date: '',
    pickup_Time: '',
    drop_Off_Location: '',
    drop_Off_Date: '',
    drop_Off_Time: '',
    confirmation_Number: '',
    cost: '',
  },
  room: {
    name: '',
    address: '',
    check_In_Date: '',
    check_In_Time: '',
    check_Out_Date: '',
    check_Out_Time: '',
    confirmation_Number: '',
    notes: '',
  },
  travel: {
    description: '',
    date: '',
    departure_Time: '',
    arrival_Time: '',
  },
  trip: {
    name: '',
  },
};

export const inputType = {
  address: 'textarea',
  agency: 'text',
  arrival_Time: 'time',
  check_In_Date: 'date',
  check_In_Time: 'time',
  check_Out_Date: 'date',
  check_Out_Time: 'time',
  confirmation_Number: 'text',
  cost: 'text',
  date: 'date',
  departure_Time: 'time',
  description: 'textarea',
  drop_Off_Date: 'date',
  drop_Off_Location: 'text',
  drop_Off_Time: 'time',
  name: 'text',
  notes: 'textarea',
  pick_Up_Date: 'date',
  pick_Up_Location: 'text',
  pickup_Time: 'time',
  place: 'text',
  return_Location: 'text',
  time: 'time',
};
