export const fields = {
  activity: {
    adate: '',
    btime: '',
    cplace: '',
    ddescription: '',
    key: '',
  },
  car: {
    apick_Up_Date: '',
    bpickup_Time: '',
    cpick_Up_Location: '',
    dagency: '',
    edrop_Off_Location: '',
    fdrop_Off_Date: '',
    gdrop_Off_Time: '',
    hconfirmation_Number: '',
    icost: '',
    jnotes: '',
    key: '',
  },
  room: {
    acheck_In_Date: '',
    bcheck_In_Time: '',
    croom: '',
    daddress: '',
    echeck_Out_Date: '',
    fcheck_Out_Time: '',
    gconfirmation_Number: '',
    hnotes: '',
    key: '',
  },
  travel: {
    adate: '',
    bdeparture_Time: '',
    cdescription: '',
    darrival_Time: '',
    key: '',
  },
  trip: {
    atrip_Name: '',
    key: '',
  },
};

export const inputType = {
  address: 'textarea',
  agency: 'text',
  arrival_Time: 'time',
  check_In_Date: 'date',
  check_In_Time: 'time',
  check_Out_Date: 'date',
  check_Out_Time: 'time',
  confirmation_Number: 'text',
  cost: 'text',
  date: 'date',
  departure_Time: 'time',
  description: 'textarea',
  drop_Off_Date: 'date',
  drop_Off_Location: 'text',
  drop_Off_Time: 'time',
  trip_Name: 'text',
  notes: 'textarea',
  pick_Up_Date: 'date',
  pick_Up_Location: 'text',
  pickup_Time: 'time',
  place: 'text',
  return_Location: 'text',
  room: 'text',
  time: 'time',
};

export const sortFields = {
  activity: 'adate',
  car: 'apick_Up_Date',
  room: 'acheckIn_Date',
  travel: 'adate',
  trip: 'atrip_Name',
};
