export const fields = {
  activity: {
    astart_Date: '',
    bstart_Time: '',
    cplace: '',
    ddescription: '',
    eend_Date: '',
    fend_Time: '',
  },
  car: {
    astart_Date: '',
    bstart_Time: '',
    cpick_Up_Location: '',
    dagency: '',
    edrop_Off_Location: '',
    fend_Date: '',
    gend_Time: '',
    hconfirmation_Number: '',
    icost: '',
    jnotes: '',
  },
  room: {
    astart_Date: '',
    bstart_Time: '',
    croom: '',
    daddress: '',
    eend_Date: '',
    fend_Time: '',
    gconfirmation_Number: '',
    hnotes: '',
  },
  travel: {
    astart_Date: '',
    bstart_Time: '',
    cdescription: '',
    dend_Date: '',
    eend_Time: '',
    fnotes: 'Record Locator: ',
  },
  trip: {
    atrip_Name: '',
    bstart_Date: '',
    cend_Date: '',
    details: '',
  },
};

export const inputType = {
  address: 'textarea',
  agency: 'text',
  confirmation_Number: 'text',
  cost: 'text',
  date: 'date',
  description: 'textarea',
  drop_Off_Location: 'text',
  end_Date: 'date',
  end_Time: 'time',
  notes: 'textarea',
  pick_Up_Location: 'text',
  place: 'text',
  return_Location: 'text',
  room: 'text',
  start_Date: 'date',
  start_Time: 'time',
  time: 'time',
  trip_Name: 'text',
};

export const labels = {
  activity: {
    astart_Date: 'astart_Date',
    bstart_Time: 'bstart_Time',
    eend_Date: 'eend_Date',
    fend_Time: 'fend_Time',
  },
  car: {
    astart_Date: 'apick_Up_Date',
    bstart_Time: 'bpick_Up_Time',
    fend_Date: 'fdrop_Off_Date',
    gend_Time: 'gdrop_Off_Time',
  },
  room: {
    astart_Date: 'acheck_In_Date',
    bstart_Time: 'bcheck_In_Time',
    eend_Date: 'echeck_Out_Date',
    fend_Time: 'fcheck_Out_Time',
  },
  travel: {
    astart_Date: 'adeparture_Date',
    bstart_Time: 'bdeparture_Time',
    dend_Date: 'darrival_Date',
    eend_Time: 'earrival_Time',
  },
  trip: {
    astart_Date: 'astart_Date',
    eend_Date: 'eend_Date',
  },
};
